baseURL = "https://co.shoogle.net/colombia/"
languageCode = "es"
title = "Colombia"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "colombia"

[taxonomies]
  shop = "shops"

